<?php

declare(strict_types=1);

namespace Nowo\FormKitBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration for FormKitBundle.
 *
 * Supports multiple coexisting configs under "configs" (each with alias, translation_domain,
 * required_label_suffix, help_modal, defaults, field_types). One config is chosen as default via "default_config".
 * Legacy root-level keys are normalized into a single "default" config when "configs" is not set.
 *
 * @author Héctor Franco Aceituno <hectorfranco@nowo.tech>
 * @copyright 2026 Nowo.tech
 */
final class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_form_kit';

    public const DEFAULT_CONFIG_NAME = 'default';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $root        = $treeBuilder->getRootNode();

        $root
            ->children()
                ->arrayNode('type_map')
                    ->info('Additional form type names (snake_case) => FQCN. Merged with built-in and optional UX types (e.g. dropzone when symfony/ux-dropzone is installed).')
                    ->defaultValue([])
                    ->useAttributeAsKey('name')
                    ->scalarPrototype()->end()
                ->end()
                ->scalarNode('default_config')
                    ->info('Name of the config to use when no config is specified (key in configs)')
                    ->defaultValue(self::DEFAULT_CONFIG_NAME)
                ->end()
                ->scalarNode('css_framework')
                    ->info('CSS framework for CssClassUtilities (column merge + class ordering): bootstrap, tailwind, foundation, none.')
                    ->defaultValue('bootstrap')
                    ->validate()
                        ->ifNotInArray(['bootstrap', 'tailwind', 'foundation', 'none'])
                        ->thenInvalid('nowo_form_kit.css_framework must be one of: bootstrap, tailwind, foundation, none.')
                    ->end()
                ->end()
                ->arrayNode('configs')
                    ->info('Named configs; each has alias and form options. Use default_config to choose the default.')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('alias')
                                ->info('Alias for this config (e.g. for reference in form types)')
                                ->isRequired()
                            ->end()
                            ->scalarNode('translation_domain')
                                ->defaultValue('messages')
                            ->end()
                            ->scalarNode('required_label_suffix')
                                ->info('Appended to the label when the field is required (e.g. " *"). Empty or null to disable.')
                                ->defaultNull()
                            ->end()
                            ->arrayNode('help_modal')
                                ->info('Default help modal configuration (used when the field option "help_modal" is enabled).')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('framework')
                                        ->info('Modal framework to use when opening from frontend.')
                                        ->defaultValue('bootstrap5')
                                    ->end()
                                    ->scalarNode('icon_html')
                                        ->info('HTML snippet inserted next to the label to trigger the help modal (fallback when ux_icon is not used or UX Icons is unavailable).')
                                        ->defaultValue('<span class="nowo-help-modal-icon" aria-hidden="true">?</span>')
                                    ->end()
                                    ->scalarNode('ux_icon')
                                        ->info('Optional. Symfony UX Icons name (e.g. lucide:circle-help). Requires symfony/ux-icons; when set and IconRendererInterface is available, overrides icon_html.')
                                        ->defaultNull()
                                    ->end()
                                    ->arrayNode('ux_icon_attributes')
                                        ->info('HTML attributes for renderIcon() when ux_icon is set (e.g. class: nowo-help-modal-icon).')
                                        ->defaultValue([])
                                        ->useAttributeAsKey('name')
                                        ->scalarPrototype()->end()
                                    ->end()
                                    ->scalarNode('trigger_class')
                                        ->info('CSS classes for the clickable trigger wrapper (after label text and required suffix). Default: circle button style.')
                                        ->defaultValue('nowo-help-modal-trigger nowo-help-modal-trigger--circle')
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('defaults')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->arrayNode('attr')
                                        ->defaultValue([])
                                        ->useAttributeAsKey('name')
                                        ->scalarPrototype()->end()
                                    ->end()
                                    ->arrayNode('row_attr')
                                        ->defaultValue([])
                                        ->useAttributeAsKey('name')
                                        ->scalarPrototype()->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('field_types')
                                ->defaultValue([])
                                ->useAttributeAsKey('name')
                                ->arrayPrototype()
                                    ->children()
                                        ->arrayNode('attr')->useAttributeAsKey('name')->scalarPrototype()->end()->end()
                                        ->arrayNode('row_attr')->useAttributeAsKey('name')->scalarPrototype()->end()->end()
                                        ->scalarNode('label')->end()
                                        ->scalarNode('placeholder')->end()
                                        ->scalarNode('help')->end()
                                        ->scalarNode('translation_domain')->end()
                                        ->arrayNode('constraints')
                                            ->info('Symfony Validator constraints for this field type (short names like NotBlank, Email, or { NotBlank: { message: "..." } } per entry). See ConstraintDefinitionFactory.')
                                            ->defaultValue([])
                                            ->prototype('variable')->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // Legacy root-level (used when configs is not set to build a single "default" config)
                ->scalarNode('translation_domain')
                    ->info('(Legacy) Used when configs is not set')
                    ->defaultValue('messages')
                ->end()
                ->scalarNode('required_label_suffix')
                    ->info('(Legacy) Suffix for required field labels when configs is not set')
                    ->defaultNull()
                ->end()
                ->arrayNode('help_modal')
                    ->info('(Legacy) Default help modal configuration when configs is not used.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('framework')
                            ->defaultValue('bootstrap5')
                        ->end()
                        ->scalarNode('icon_html')
                            ->defaultValue('<span class="nowo-help-modal-icon" aria-hidden="true">?</span>')
                        ->end()
                        ->scalarNode('ux_icon')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('ux_icon_attributes')
                            ->defaultValue([])
                            ->useAttributeAsKey('name')
                            ->scalarPrototype()->end()
                        ->end()
                        ->scalarNode('trigger_class')
                            ->defaultValue('nowo-help-modal-trigger nowo-help-modal-trigger--circle')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('defaults')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('attr')->defaultValue([])->useAttributeAsKey('name')->scalarPrototype()->end()->end()
                        ->arrayNode('row_attr')->defaultValue([])->useAttributeAsKey('name')->scalarPrototype()->end()->end()
                    ->end()
                ->end()
                ->arrayNode('field_types')
                    ->defaultValue([])
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->arrayNode('attr')->useAttributeAsKey('name')->scalarPrototype()->end()->end()
                            ->arrayNode('row_attr')->useAttributeAsKey('name')->scalarPrototype()->end()->end()
                            ->scalarNode('label')->end()
                            ->scalarNode('placeholder')->end()
                            ->scalarNode('help')->end()
                            ->scalarNode('translation_domain')->end()
                            ->arrayNode('constraints')
                                ->defaultValue([])
                                ->prototype('variable')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
